name: Push To Master
on:
  push:
    branches: [master]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: ./
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: npm i
  lint:
      runs-on: ubuntu-latest
      steps:
      - run: |
          npm run format
          npm run lint
  test:
      runs-on: ubuntu-latest
      steps:
      - run: npm run test
  build:
      runs-on: ubuntu-latest
      steps:
      - run: npm run build
