name: Push To Master
on:
  push:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
  lint:
      runs-on: ubuntu-latest
      steps:
      - run: |
          npm run format
          npm run lint
  test:
      runs-on: ubuntu-latest
      steps:
      - run: npm run test
  build:
      runs-on: ubuntu-latest
      steps:
      - run: npm run build
